# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
r_github_packages: r-lib/remotes#340
cache: packages

r_binary_packages:
  # install locally to avoid rev dep
  - covr # code coverage check
  # - lintr # code lint

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
    - travis
