// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// round_down_core
IntegerVector round_down_core(IntegerVector a, IntegerVector b);
RcppExport SEXP padr_round_down_core(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    __result = Rcpp::wrap(round_down_core(a, b));
    return __result;
END_RCPP
}
// round_up_core
IntegerVector round_up_core(IntegerVector a, IntegerVector b);
RcppExport SEXP padr_round_up_core(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    __result = Rcpp::wrap(round_up_core(a, b));
    return __result;
END_RCPP
}
