# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

round_down_core <- function(a, b) {
    .Call('_padr_round_down_core', PACKAGE = 'padr', a, b)
}

round_down_core_prev <- function(a, b) {
    .Call('_padr_round_down_core_prev', PACKAGE = 'padr', a, b)
}

round_up_core <- function(a, b) {
    .Call('_padr_round_up_core', PACKAGE = 'padr', a, b)
}

round_up_core_prev <- function(a, b) {
    .Call('_padr_round_up_core_prev', PACKAGE = 'padr', a, b)
}

